package dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pojo.Trail;

public interface TrailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail
     *
     * @mbg.generated
     */
    int insert(Trail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail
     *
     * @mbg.generated
     */
    int insertSelective(Trail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail
     *
     * @mbg.generated
     */
    Trail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Trail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Trail row);
    
    List<Trail> selectAll(Trail trail);

	int updateEndTimeByPrimaryKey(Trail trail);

	List<Map> getDetailByUid(@Param("uid")Integer uid);
    
}