package dao;

import java.util.List;

import pojo.TrailDetail;

public interface TrailDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail_detail
     *
     * @mbg.generated
     */
    int insert(TrailDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail_detail
     *
     * @mbg.generated
     */
    int insertSelective(TrailDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail_detail
     *
     * @mbg.generated
     */
    TrailDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TrailDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trail_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TrailDetail row);

	List<TrailDetail> selectAll(TrailDetail trailDetail);
}