package dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import pojo.View;

@Repository
public interface ViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbggenerated
     */
    int insert(View record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbggenerated
     */
    int insertSelective(View record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbggenerated
     */
    View selectByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(View record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(View record);

	List<View> selectAll(View view);

	List<View> selectNearest(View view);
}