package pojo;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbggenerated
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apassword
     *
     * @mbggenerated
     */
    private String apassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.atname
     *
     * @mbggenerated
     */
    private String atname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aphone
     *
     * @mbggenerated
     */
    private String aphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.asex
     *
     * @mbggenerated
     */
    private String asex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.amarry
     *
     * @mbggenerated
     */
    private String amarry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aloc
     *
     * @mbggenerated
     */
    private String aloc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbggenerated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbggenerated
     */
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apassword
     *
     * @return the value of admin.apassword
     *
     * @mbggenerated
     */
    public String getApassword() {
        return apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apassword
     *
     * @param apassword the value for admin.apassword
     *
     * @mbggenerated
     */
    public void setApassword(String apassword) {
        this.apassword = apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.atname
     *
     * @return the value of admin.atname
     *
     * @mbggenerated
     */
    public String getAtname() {
        return atname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.atname
     *
     * @param atname the value for admin.atname
     *
     * @mbggenerated
     */
    public void setAtname(String atname) {
        this.atname = atname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aphone
     *
     * @return the value of admin.aphone
     *
     * @mbggenerated
     */
    public String getAphone() {
        return aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aphone
     *
     * @param aphone the value for admin.aphone
     *
     * @mbggenerated
     */
    public void setAphone(String aphone) {
        this.aphone = aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.asex
     *
     * @return the value of admin.asex
     *
     * @mbggenerated
     */
    public String getAsex() {
        return asex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.asex
     *
     * @param asex the value for admin.asex
     *
     * @mbggenerated
     */
    public void setAsex(String asex) {
        this.asex = asex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.amarry
     *
     * @return the value of admin.amarry
     *
     * @mbggenerated
     */
    public String getAmarry() {
        return amarry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.amarry
     *
     * @param amarry the value for admin.amarry
     *
     * @mbggenerated
     */
    public void setAmarry(String amarry) {
        this.amarry = amarry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aloc
     *
     * @return the value of admin.aloc
     *
     * @mbggenerated
     */
    public String getAloc() {
        return aloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aloc
     *
     * @param aloc the value for admin.aloc
     *
     * @mbggenerated
     */
    public void setAloc(String aloc) {
        this.aloc = aloc;
    }

	@Override
	public String toString() {
		return "Admin [aname=" + aname + ", apassword=" + apassword + ", atname=" + atname + ", aphone=" + aphone
				+ ", asex=" + asex + ", amarry=" + amarry + ", aloc=" + aloc + "]";
	}
    
    
}