package pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.tid
     *
     * @mbggenerated
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ccontent
     *
     * @mbggenerated
     */
    private String ccontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cid
     *
     * @return the value of comment.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cid
     *
     * @param cid the value for comment.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.tid
     *
     * @return the value of comment.tid
     *
     * @mbggenerated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.tid
     *
     * @param tid the value for comment.tid
     *
     * @mbggenerated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.uid
     *
     * @return the value of comment.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.uid
     *
     * @param uid the value for comment.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ccontent
     *
     * @return the value of comment.ccontent
     *
     * @mbggenerated
     */
    public String getCcontent() {
        return ccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ccontent
     *
     * @param ccontent the value for comment.ccontent
     *
     * @mbggenerated
     */
    public void setCcontent(String ccontent) {
        this.ccontent = ccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ctime
     *
     * @return the value of comment.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ctime
     *
     * @param ctime the value for comment.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	@Override
	public String toString() {
		return "Comment [cid=" + cid + ", tid=" + tid + ", uid=" + uid + ", ccontent=" + ccontent + ", ctime=" + ctime
				+ "]";
	}
    
}