package pojo;

import java.util.Date;

public class Trail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.beginTime
     *
     * @mbg.generated
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.beginPosition
     *
     * @mbg.generated
     */
    private String beginposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.endPosition
     *
     * @mbg.generated
     */
    private String endposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.TOTAL_TIME
     *
     * @mbg.generated
     */
    private String totalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.TOTAL_DISTANCE
     *
     * @mbg.generated
     */
    private String totalDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail.AVG_SPEED
     *
     * @mbg.generated
     */
    private String avgSpeed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.id
     *
     * @return the value of trail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.id
     *
     * @param id the value for trail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.uid
     *
     * @return the value of trail.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.uid
     *
     * @param uid the value for trail.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.beginTime
     *
     * @return the value of trail.beginTime
     *
     * @mbg.generated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.beginTime
     *
     * @param begintime the value for trail.beginTime
     *
     * @mbg.generated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.endTime
     *
     * @return the value of trail.endTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.endTime
     *
     * @param endtime the value for trail.endTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.beginPosition
     *
     * @return the value of trail.beginPosition
     *
     * @mbg.generated
     */
    public String getBeginposition() {
        return beginposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.beginPosition
     *
     * @param beginposition the value for trail.beginPosition
     *
     * @mbg.generated
     */
    public void setBeginposition(String beginposition) {
        this.beginposition = beginposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.endPosition
     *
     * @return the value of trail.endPosition
     *
     * @mbg.generated
     */
    public String getEndposition() {
        return endposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.endPosition
     *
     * @param endposition the value for trail.endPosition
     *
     * @mbg.generated
     */
    public void setEndposition(String endposition) {
        this.endposition = endposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.TOTAL_TIME
     *
     * @return the value of trail.TOTAL_TIME
     *
     * @mbg.generated
     */
    public String getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.TOTAL_TIME
     *
     * @param totalTime the value for trail.TOTAL_TIME
     *
     * @mbg.generated
     */
    public void setTotalTime(String totalTime) {
        this.totalTime = totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.TOTAL_DISTANCE
     *
     * @return the value of trail.TOTAL_DISTANCE
     *
     * @mbg.generated
     */
    public String getTotalDistance() {
        return totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.TOTAL_DISTANCE
     *
     * @param totalDistance the value for trail.TOTAL_DISTANCE
     *
     * @mbg.generated
     */
    public void setTotalDistance(String totalDistance) {
        this.totalDistance = totalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail.AVG_SPEED
     *
     * @return the value of trail.AVG_SPEED
     *
     * @mbg.generated
     */
    public String getAvgSpeed() {
        return avgSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail.AVG_SPEED
     *
     * @param avgSpeed the value for trail.AVG_SPEED
     *
     * @mbg.generated
     */
    public void setAvgSpeed(String avgSpeed) {
        this.avgSpeed = avgSpeed;
    }
}