package pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TrailDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.TR_ID
     *
     * @mbg.generated
     */
    private Integer trId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.TR_LAT
     *
     * @mbg.generated
     */
    private BigDecimal trLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.TR_LON
     *
     * @mbg.generated
     */
    private BigDecimal trLon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.TR_TIME
     *
     * @mbg.generated
     */
    private Date trTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.spare1
     *
     * @mbg.generated
     */
    private String spare1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.spare2
     *
     * @mbg.generated
     */
    private String spare2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trail_detail.spare3
     *
     * @mbg.generated
     */
    private String spare3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.id
     *
     * @return the value of trail_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.id
     *
     * @param id the value for trail_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.TR_ID
     *
     * @return the value of trail_detail.TR_ID
     *
     * @mbg.generated
     */
    public Integer getTrId() {
        return trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.TR_ID
     *
     * @param trId the value for trail_detail.TR_ID
     *
     * @mbg.generated
     */
    public void setTrId(Integer trId) {
        this.trId = trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.TR_LAT
     *
     * @return the value of trail_detail.TR_LAT
     *
     * @mbg.generated
     */
    public BigDecimal getTrLat() {
        return trLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.TR_LAT
     *
     * @param trLat the value for trail_detail.TR_LAT
     *
     * @mbg.generated
     */
    public void setTrLat(BigDecimal trLat) {
        this.trLat = trLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.TR_LON
     *
     * @return the value of trail_detail.TR_LON
     *
     * @mbg.generated
     */
    public BigDecimal getTrLon() {
        return trLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.TR_LON
     *
     * @param trLon the value for trail_detail.TR_LON
     *
     * @mbg.generated
     */
    public void setTrLon(BigDecimal trLon) {
        this.trLon = trLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.TR_TIME
     *
     * @return the value of trail_detail.TR_TIME
     *
     * @mbg.generated
     */
    public Date getTrTime() {
        return trTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.TR_TIME
     *
     * @param trTime the value for trail_detail.TR_TIME
     *
     * @mbg.generated
     */
    public void setTrTime(Date trTime) {
        this.trTime = trTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.spare1
     *
     * @return the value of trail_detail.spare1
     *
     * @mbg.generated
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.spare1
     *
     * @param spare1 the value for trail_detail.spare1
     *
     * @mbg.generated
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.spare2
     *
     * @return the value of trail_detail.spare2
     *
     * @mbg.generated
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.spare2
     *
     * @param spare2 the value for trail_detail.spare2
     *
     * @mbg.generated
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trail_detail.spare3
     *
     * @return the value of trail_detail.spare3
     *
     * @mbg.generated
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trail_detail.spare3
     *
     * @param spare3 the value for trail_detail.spare3
     *
     * @mbg.generated
     */
    public void setSpare3(String spare3) {
        this.spare3 = spare3;
    }
}