package pojo;

import java.util.Date;

public class Travels {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.tid
	 * @mbggenerated
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.ttitle
	 * @mbggenerated
	 */
	private String ttitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.ttime
	 * @mbggenerated
	 */
	private Date ttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.tcontent
	 * @mbggenerated
	 */
	private String tcontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.vid
	 * @mbggenerated
	 */
	private Integer vid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg1
	 * @mbggenerated
	 */
	private String timg1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg2
	 * @mbggenerated
	 */
	private String timg2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg3
	 * @mbggenerated
	 */
	private String timg3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg4
	 * @mbggenerated
	 */
	private String timg4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg5
	 * @mbggenerated
	 */
	private String timg5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg6
	 * @mbggenerated
	 */
	private String timg6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg7
	 * @mbggenerated
	 */
	private String timg7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg8
	 * @mbggenerated
	 */
	private String timg8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column travels.timg9
	 * @mbggenerated
	 */
	private String timg9;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.tid
	 * @return  the value of travels.tid
	 * @mbggenerated
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.tid
	 * @param tid  the value for travels.tid
	 * @mbggenerated
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.ttitle
	 * @return  the value of travels.ttitle
	 * @mbggenerated
	 */
	public String getTtitle() {
		return ttitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.ttitle
	 * @param ttitle  the value for travels.ttitle
	 * @mbggenerated
	 */
	public void setTtitle(String ttitle) {
		this.ttitle = ttitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.ttime
	 * @return  the value of travels.ttime
	 * @mbggenerated
	 */
	public Date getTtime() {
		return ttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.ttime
	 * @param ttime  the value for travels.ttime
	 * @mbggenerated
	 */
	public void setTtime(Date ttime) {
		this.ttime = ttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.tcontent
	 * @return  the value of travels.tcontent
	 * @mbggenerated
	 */
	public String getTcontent() {
		return tcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.tcontent
	 * @param tcontent  the value for travels.tcontent
	 * @mbggenerated
	 */
	public void setTcontent(String tcontent) {
		this.tcontent = tcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.vid
	 * @return  the value of travels.vid
	 * @mbggenerated
	 */
	public Integer getVid() {
		return vid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.vid
	 * @param vid  the value for travels.vid
	 * @mbggenerated
	 */
	public void setVid(Integer vid) {
		this.vid = vid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.uid
	 * @return  the value of travels.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.uid
	 * @param uid  the value for travels.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg1
	 * @return  the value of travels.timg1
	 * @mbggenerated
	 */
	public String getTimg1() {
		return timg1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg1
	 * @param timg1  the value for travels.timg1
	 * @mbggenerated
	 */
	public void setTimg1(String timg1) {
		this.timg1 = timg1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg2
	 * @return  the value of travels.timg2
	 * @mbggenerated
	 */
	public String getTimg2() {
		return timg2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg2
	 * @param timg2  the value for travels.timg2
	 * @mbggenerated
	 */
	public void setTimg2(String timg2) {
		this.timg2 = timg2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg3
	 * @return  the value of travels.timg3
	 * @mbggenerated
	 */
	public String getTimg3() {
		return timg3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg3
	 * @param timg3  the value for travels.timg3
	 * @mbggenerated
	 */
	public void setTimg3(String timg3) {
		this.timg3 = timg3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg4
	 * @return  the value of travels.timg4
	 * @mbggenerated
	 */
	public String getTimg4() {
		return timg4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg4
	 * @param timg4  the value for travels.timg4
	 * @mbggenerated
	 */
	public void setTimg4(String timg4) {
		this.timg4 = timg4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg5
	 * @return  the value of travels.timg5
	 * @mbggenerated
	 */
	public String getTimg5() {
		return timg5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg5
	 * @param timg5  the value for travels.timg5
	 * @mbggenerated
	 */
	public void setTimg5(String timg5) {
		this.timg5 = timg5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg6
	 * @return  the value of travels.timg6
	 * @mbggenerated
	 */
	public String getTimg6() {
		return timg6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg6
	 * @param timg6  the value for travels.timg6
	 * @mbggenerated
	 */
	public void setTimg6(String timg6) {
		this.timg6 = timg6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg7
	 * @return  the value of travels.timg7
	 * @mbggenerated
	 */
	public String getTimg7() {
		return timg7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg7
	 * @param timg7  the value for travels.timg7
	 * @mbggenerated
	 */
	public void setTimg7(String timg7) {
		this.timg7 = timg7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg8
	 * @return  the value of travels.timg8
	 * @mbggenerated
	 */
	public String getTimg8() {
		return timg8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg8
	 * @param timg8  the value for travels.timg8
	 * @mbggenerated
	 */
	public void setTimg8(String timg8) {
		this.timg8 = timg8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column travels.timg9
	 * @return  the value of travels.timg9
	 * @mbggenerated
	 */
	public String getTimg9() {
		return timg9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column travels.timg9
	 * @param timg9  the value for travels.timg9
	 * @mbggenerated
	 */
	public void setTimg9(String timg9) {
		this.timg9 = timg9;
	}
}