package pojo;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uname
	 * @mbggenerated
	 */
	private String uname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.upassword
	 * @mbggenerated
	 */
	private String upassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.utname
	 * @mbggenerated
	 */
	private String utname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uphone
	 * @mbggenerated
	 */
	private String uphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.usex
	 * @mbggenerated
	 */
	private String usex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uloc
	 * @mbggenerated
	 */
	private String uloc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.utime
	 * @mbggenerated
	 */
	private Date utime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.usig
	 * @mbggenerated
	 */
	private String usig;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uimg
	 * @mbggenerated
	 */
	private String uimg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uid
	 * @return  the value of user.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uid
	 * @param uid  the value for user.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uname
	 * @return  the value of user.uname
	 * @mbggenerated
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uname
	 * @param uname  the value for user.uname
	 * @mbggenerated
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.upassword
	 * @return  the value of user.upassword
	 * @mbggenerated
	 */
	public String getUpassword() {
		return upassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.upassword
	 * @param upassword  the value for user.upassword
	 * @mbggenerated
	 */
	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.utname
	 * @return  the value of user.utname
	 * @mbggenerated
	 */
	public String getUtname() {
		return utname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.utname
	 * @param utname  the value for user.utname
	 * @mbggenerated
	 */
	public void setUtname(String utname) {
		this.utname = utname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uphone
	 * @return  the value of user.uphone
	 * @mbggenerated
	 */
	public String getUphone() {
		return uphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uphone
	 * @param uphone  the value for user.uphone
	 * @mbggenerated
	 */
	public void setUphone(String uphone) {
		this.uphone = uphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.usex
	 * @return  the value of user.usex
	 * @mbggenerated
	 */
	public String getUsex() {
		return usex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.usex
	 * @param usex  the value for user.usex
	 * @mbggenerated
	 */
	public void setUsex(String usex) {
		this.usex = usex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uloc
	 * @return  the value of user.uloc
	 * @mbggenerated
	 */
	public String getUloc() {
		return uloc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uloc
	 * @param uloc  the value for user.uloc
	 * @mbggenerated
	 */
	public void setUloc(String uloc) {
		this.uloc = uloc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.utime
	 * @return  the value of user.utime
	 * @mbggenerated
	 */
	public Date getUtime() {
		return utime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.utime
	 * @param utime  the value for user.utime
	 * @mbggenerated
	 */
	public void setUtime(Date utime) {
		this.utime = utime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.usig
	 * @return  the value of user.usig
	 * @mbggenerated
	 */
	public String getUsig() {
		return usig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.usig
	 * @param usig  the value for user.usig
	 * @mbggenerated
	 */
	public void setUsig(String usig) {
		this.usig = usig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uimg
	 * @return  the value of user.uimg
	 * @mbggenerated
	 */
	public String getUimg() {
		return uimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uimg
	 * @param uimg  the value for user.uimg
	 * @mbggenerated
	 */
	public void setUimg(String uimg) {
		this.uimg = uimg;
	}

	@Override
	public String toString() {
		return "User [uid=" + uid + ", uname=" + uname + ", upassword=" + upassword + ", utname=" + utname + ", uphone="
				+ uphone + ", usex=" + usex + ", uloc=" + uloc + ", utime=" + utime + ", usig=" + usig + ", uimg="
				+ uimg + "]";
	}
	
}