package pojo;

import java.math.BigDecimal;

public class View {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.vid
     *
     * @mbggenerated
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.vname
     *
     * @mbggenerated
     */
    private String vname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.vlat
     *
     * @mbggenerated
     */
    private BigDecimal vlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.vlon
     *
     * @mbggenerated
     */
    private BigDecimal vlon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.vmessage
     *
     * @mbggenerated
     */
    private String vmessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.vid
     *
     * @return the value of view.vid
     *
     * @mbggenerated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.vid
     *
     * @param vid the value for view.vid
     *
     * @mbggenerated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.vname
     *
     * @return the value of view.vname
     *
     * @mbggenerated
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.vname
     *
     * @param vname the value for view.vname
     *
     * @mbggenerated
     */
    public void setVname(String vname) {
        this.vname = vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.vlat
     *
     * @return the value of view.vlat
     *
     * @mbggenerated
     */
    public BigDecimal getVlat() {
        return vlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.vlat
     *
     * @param vlat the value for view.vlat
     *
     * @mbggenerated
     */
    public void setVlat(BigDecimal vlat) {
        this.vlat = vlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.vlon
     *
     * @return the value of view.vlon
     *
     * @mbggenerated
     */
    public BigDecimal getVlon() {
        return vlon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.vlon
     *
     * @param vlon the value for view.vlon
     *
     * @mbggenerated
     */
    public void setVlon(BigDecimal vlon) {
        this.vlon = vlon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.vmessage
     *
     * @return the value of view.vmessage
     *
     * @mbggenerated
     */
    public String getVmessage() {
        return vmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.vmessage
     *
     * @param vmessage the value for view.vmessage
     *
     * @mbggenerated
     */
    public void setVmessage(String vmessage) {
        this.vmessage = vmessage;
    }
}